name: Deploy to Google Cloud Run

on:
  pull_request:
    types: [closed]
    branches:
      - "main"

jobs:
  setup-build-deploy:
    name: Setup, Build and Deploy GCR
    runs-on: ubuntu-latest
    environment: production
    env:
      DOCKER_IMAGE_LOCATION: ${{secrets.GAR_REGION}}-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/${{secrets.GAR_REPOSITORY}}/${{secrets.DOCKER_IMAGE}}
    
    if: github.event.pull_request.merged
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - id: auth 
      name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{secrets.GCP_CREDENTIALS}}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
          
    - name: Build Docker image
      run: |-
        gcloud auth configure-docker ${{secrets.GAR_REGION}}-docker.pkg.dev
        docker build -t ${{secrets.DOCKER_IMAGE}} .
        docker tag ${{secrets.DOCKER_IMAGE}} ${{env.DOCKER_IMAGE_LOCATION}}:lastest
        
    - name: Push the Docker image to Google Artifact Registry
      run: |-
        docker push ${{env.DOCKER_IMAGE_LOCATION}}:lastest
      
    - name: Deploy to Google Cloud Run
      run: gcloud run deploy ${{secrets.APP_NAME}} --image ${{env.DOCKER_IMAGE_LOCATION}}:lastest --platform managed --allow-unauthenticated --region ${{secrets.GCP_PROJECT_REGION}}
