name: Deploy to Google Cloud Run

on:
  pull_request:
    types: [closed]
    branches:
      - "main"

jobs:
  setup-build-deploy:
    name: Setup, Build and Deploy GCR
    runs-on: ubuntu-latest
    environment: production
    
    if: github.event.pull_request.merged
    steps:
    - uses: actions/checkout@v2
    
    - id: Auth 
      name: Authenticate to Google Cloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
          credentials_json: ${{secrets.GCP_CREDENTIALS}}
          
    - name: Build
      run: gcloud builds submit --tag gcr.io/${{secrets.GCP_PROJECT_ID}}/${{secrets.APP_NAME}}:$GITHUB_SHA
      
    - name: Deploy to Google Cloud Run
      run: gcloud run deploy ${{secrets.APP_NAME}} --image gcr.io/${{secrets.GCP_PROJECT_ID}}/${{secrets.APP_NAME}}:$GITHUB_SHA --platform managed --region ${{secrets.GCP_PROJECT_REGION}} --allow-unauthenticated
